version: "2"
services:
  rsnapshot-backup:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
          buildno: 1
    volumes: 
      - /root/data-backup:/snapshot
      - /root/.ssh:/root/.ssh
    environment: 
      - BACKUP_DIRECTORIES=root@164.90.182.3:/home/debian/samba /snapshot
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    